apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: gitlab-https
      port: 80
      targetPort: 80
    nodePort: 30080        
  type: NodePort
