apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-volume
  namespace: gitlab
spec:
  storageClassName: gitlab
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/gitlab"
