apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pv-claim
  namespace: gitlab
spec:
  storageClassName: gitlab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
